### ISSUE TITLE
Deactivate Scrolling

### ISSUE THREAD

**Issue by abflussengel** [codebushi/gatsby-starter-dimension#22]
Hi, first of all thank you for making this template accessible. 
I wanted to ask if there is a way to deactivate the scrolling? 
Thank you in advance.

**Comment by ChangoMan** [comment]
Hey, you can probably set `overflow-y: hidden` on the `<body>` using CSS. This should disable the scrolling, but be careful when using this because it will cut off your content on shorter screens.
