### ISSUE TITLE
Email Setting

### ISSUE THREAD

**Issue by akshatgit** [codebushi/gatsby-starter-dimension#24]
Hi, thank you for this awesome template. I am a complete beginner in Gatsby. I wanted to know the settings for email/contacts page. I'm not using netlify.

**Comment by ChangoMan** [comment]
Hey, glad you like the template. By default there are no built in settings for the emailing. You are free to choose your own service to handle this. Maybe something like https://formspree.io or https://formkeep.com? I've only used Netlify so I can't recommend anything. Hope this helps

**Comment by akshatgit** [comment]
Thanks a lot! Used Formspree, it is working great.
