### ISSUE TITLE
Blur/transitions slow in Firefox

### ISSUE THREAD

**Issue by lukebelliveau** [codebushi/gatsby-starter-dimension#32]
Opening and closing the sections (Intro/Work/About/Contact) is really slow on Firefox. Looks great on Chrome & Safari. Not sure why.

Of course you're under no obligation to fix this, just thought I'd let you know. Thanks for the great theme 😃 !

**Comment by ChangoMan** [comment]
Interesting, I just checked Firefox and it is quite slow. I'll try to investigate further, thanks for pointing this out!

**Comment by ChangoMan** [comment]
Looks like that blur CSS transition was slow in Firefox. I've disabled it for now, so this should be fixed.
