### ISSUE TITLE
Lock files belong in git

### ISSUE THREAD

**Issue by chmac** [codebushi/gatsby-starter-dimension#33]
Firstly, thanks for the work on this starter, it's awesome.

Just noticed that the lock files are excluded from git. I know [yarn recommends](https://yarnpkg.com/lang/en/docs/yarn-lock/#toc-check-into-source-control) keeping `yarn.lock` in git, and I imagine it's the same for npm. Happy to whip up a PR putting the `yarn.lock` file into the repo if you like. Or at least removing it from the `.gitignore`. I didn't realise at first that it wasn't included...

**Comment by ChangoMan** [comment]
Thanks! I've updated the `.gitignore` and added the yarn lock file
